#pragma once

#include <stdbool.h>
#include <stdint.h>

#define IRRIGATION_FIRMWARE_VERSION "0.2.4-status-led-zigbee-option"

#define IRRIGATION_MAX_LINES 8
#define IRRIGATION_DEFAULT_LINE_COUNT 3
#define IRRIGATION_MAX_SCHEDULES_PER_LINE 4

#define IRRIGATION_MODE_BUTTON_GPIO 9
#define IRRIGATION_MODE_BUTTON_ACTIVE_LEVEL 0
#define IRRIGATION_MODE_HOLD_MS 1500

#define IRRIGATION_STATUS_LED_GPIO 8
#define IRRIGATION_STATUS_LED_ENABLED true

#define IRRIGATION_DEFAULT_INTERLOCK true
#define IRRIGATION_DEFAULT_ZIGBEE_ROUTER_WITH_MQTT false
#define IRRIGATION_DEFAULT_RELAY_ACTIVE_HIGH true
#define IRRIGATION_DEFAULT_DURATION_SECONDS 300

static const int IRRIGATION_DEFAULT_RELAY_GPIOS[IRRIGATION_DEFAULT_LINE_COUNT] = {
    2,
    3,
    10,
};

static const char *const IRRIGATION_DEFAULT_LINE_NAMES[IRRIGATION_DEFAULT_LINE_COUNT] = {
    "line_1",
    "line_2",
    "line_3",
};
